# -*- coding: utf-8 -*-
"""poets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kjJt1c3oNULu3C5ReivF7obp-Q3Wg-Hg
"""

pip install --upgrade "tensorflow==1.7.*"

import tensorflow as tf
import os

from google.colab import drive
drive.mount('/content/drive/')

working_path = "/content/drive/My Drive/cats"
!ls "/content/drive/My Drive/cats"

os.chdir('/content/drive/My Drive')

if not os.path.isdir("tensorflow-for-poets-2"):
  !git clone https://github.com/googlecodelabs/tensorflow-for-poets-2

# Change working directory
os.chdir('tensorflow-for-poets-2')

# Commented out IPython magic to ensure Python compatibility.
# %run scripts/retrain -h

# Commented out IPython magic to ensure Python compatibility.
# %run scripts/retrain.py   \
  --bottleneck_dir=tf_files/bottlenecks   \
  --how_many_training_steps=500   \
  --model_dir=tf_files/models/   \
  --summaries_dir=tf_files/training_summaries/mobilenet_0.50_160   \
  --output_graph=tf_files/retrained_graph.pb   \
  --output_labels=tf_files/retrained_labels.txt   \
  --learning_rate=0.01   \
  --architecture=mobilenet_0.50_160   \
  --image_dir=../cats \
  --flip_left_right \
  --random_crop=10 \
  --random_scale=10 \
  --random_brightness=10

!ls -lth tf_files

!head tf_files/retrained_labels.txt

!wget https://www.universodegatos.com/wp-content/themes/yootheme/cache/gatos-persas-8b14992f.jpeg -O testea.jpg

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
from PIL import Image
# %matplotlib inline 
plt.imshow(Image.open('testea.jpg'))
plt.axis('off')

# Commented out IPython magic to ensure Python compatibility.
# %run scripts/label_image \
    --graph=tf_files/retrained_graph.pb  \
    --input_height=160 \
    --input_width=160 \
    --image=testea.jpg